In [17]:
from Predictions import Predictions
import matplotlib.pyplot as plt
from ete3 import PhyloTree, TreeStyle
import pandas as pd
import ete3
from ete3 import TreeStyle, PhyloTree, Tree, faces, NodeStyle, AttrFace, TextFace
from ete3.treeview.faces import add_face_to_node

In [1]:
def read_fasta(file):
    seqs = []
    names = []
    seq = ""

    with open(file, "r") as f:
        lines = f.readlines()
    
    for line in lines:
        if line.startswith(">"):
            names.append(line.strip().replace(">",""))
            if len(names) > 1:
                seqs.append(seq)
                seq = ""
        else:
            seq += line.strip()

    seqs.append(seq)
    return pd.DataFrame({"name" : names, "aa_seq" : seqs})

In [2]:
import os
os.chdir("/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/saccharmycotina_TFs/analysis_scripts")

In [3]:
aa_colors = {
    # Purples
    'F': '#ECA758',  
    'W': '#306BAC',
    'L': '#562F7F',

    # Reds
    'D': '#D04741', 
    'E': '#EAA3A7', 

    # Blues
    'K': '#52B0E1', 
    'R': '#52B0E1', 

    # black
    'S': '#000000', 
    'P': '#000000',

    # greys
    'A': '#787878',
    'V': '#787878',
    'I': '#787878',
    'M': '#787878',
    'T': '#787878',
    'G': '#787878',
    'C': '#787878',
    'N': '#787878',
    'Q': '#787878',
    'H': '#787878',  
    'Y': '#787878', 
    '-': "#000000"
}

aa_colors = {
    # Oranges
    'F': '#ff8000',  
    'W': '#ff8000',
    'L': '#ff8000',

    # Reds
    'D': '#ff3333', 
    'E': '#ff3333', 

    # Blues
    'K': '#009933', 
    'R': '#009933', 

    # black
    'S': '#000000', 
    'P': '#000000',

    # greys
    'A': '#595959',
    'V': '#595959',
    'I': '#595959',
    'M': '#595959',
    'T': '#595959',
    'G': '#595959',
    'C': '#595959',
    'N': '#595959',
    'Q': '#595959',
    'H': '#595959',  
    'Y': '#595959', 
    '-': "#000000"
}

In [7]:
folder = "Gcn4"
prediction = Predictions(f"../{folder}/{folder}_orthologs_consensus_predictions.pkl.gz",
                        "/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/phylogenetic_data/1175taxa_1403OGs_astral_length_rooted_lpp_added.tre",
                        "/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/phylogenetic_data/ALL_NAMES_FILE.xlsx")

In [13]:
fg_colors = {
    # Purples
    'F': '#FFFFFF',  
    'W': '#000000',
    'L': '#000000',

    # Reds
    'D': '#000000', 
    'E': '#000000', 

    # Blues
    'K': '#000000', 
    'R': '#000000', 

    # black
    'S': '#000000', 
    'P': '#000000',

    # greys
    'A': '#000000',
    'V': '#000000',
    'I': '#000000',
    'M': '#000000',
    'T': '#000000',
    'G': '#000000',
    'C': '#000000',
    'N': '#000000',
    'Q': '#000000',
    'H': '#000000',  
    'Y': '#000000', 
    '-': "#000000"
}

bg_colors = {
    # Oranges
    'F': '#000000',  
    'W': '#FFFFFF',
    'L': '#FFFFFF',

    # Reds
    'D': '#FFFFFF', 
    'E': '#FFFFFF', 

    # Blues
    'K': '#FFFFFF', 
    'R': '#FFFFFF', 

    # black
    'S': '#FFFFFF', 
    'P': '#FFFFFF',

    # greys
    'A': '#FFFFFF',
    'V': '#FFFFFF',
    'I': '#FFFFFF',
    'M': '#FFFFFF',
    'T': '#FFFFFF',
    'G': '#FFFFFF',
    'C': '#FFFFFF',
    'N': '#FFFFFF',
    'Q': '#FFFFFF',
    'H': '#FFFFFF',  
    'Y': '#FFFFFF', 
    '-': "#FFFFFF"
}

bg_colors_2 = {
    # Oranges
    'F': "#000000",  
    'W': "#3DCBFAFF",
    'L': '#3DCBFAFF',

    # Reds
    'D': '#3DCBFAFF', 
    'E': '#3DCBFAFF', 

    # Blues
    'K': '#3DCBFAFF', 
    'R': '#3DCBFAFF', 

    # black
    'S': '#3DCBFAFF', 
    'P': '#3DCBFAFF',

    # greys
    'A': '#3DCBFAFF',
    'V': '#3DCBFAFF',
    'I': '#3DCBFAFF',
    'M': '#3DCBFAFF',
    'T': '#3DCBFAFF',
    'G': '#3DCBFAFF',
    'C': '#3DCBFAFF',
    'N': '#3DCBFAFF',
    'Q': '#3DCBFAFF',
    'H': '#3DCBFAFF',  
    'Y': '#3DCBFAFF', 
    '-': "#3DCBFAFF"
}

In [9]:
def get_coords(alignment, name, seq_df):

    alignment_df = read_fasta(alignment)
    subset_alignment_df = alignment_df[alignment_df['name'] == name ]

    subset_seq_df = seq_df[seq_df['name'] == name]
    
    start, end = subset_seq_df["AD_coords"].values[0][0]
    ad_seq = subset_seq_df['sequence'].values[0][start:end]
    print(ad_seq)
    i = 0
    start = -1
    for j, aa in enumerate(subset_alignment_df['aa_seq'].values[0]):
        if aa == ad_seq[i]:
            if start == -1:
                start = j
            i += 1
        elif aa == "-":
            continue
        else:
            i = 0
            start = -1
        
        if i == len(ad_seq):
            end = j
            return start, end

In [5]:

bg_colors_2 = {
    # Oranges
    'F': "#000000",  
    'W': "lightblue",
    'L': 'lightblue',

    # Reds
    'D': 'lightblue', 
    'E': 'lightblue', 

    # Blues
    'K': 'lightblue', 
    'R': 'lightblue', 

    # black
    'S': 'lightblue', 
    'P': 'lightblue',

    # greys
    'A': 'lightblue',
    'V': 'lightblue',
    'I': 'lightblue',
    'M': 'lightblue',
    'T': 'lightblue',
    'G': 'lightblue',
    'C': 'lightblue',
    'N': 'lightblue',
    'Q': 'lightblue',
    'H': 'lightblue',  
    'Y': 'lightblue', 
    '-': "lightblue"
}

# Ancestral reconstruction 1

In [8]:
names = ["Priceomyces_carsonii", "Schwanniomyces_occidentalis_var._persoonii"] #, "Candida_fluviatilis"] #, "Candida_boidinii"]
subset = prediction.get_species_subset(names)[1]
f_prefix = names[0]
genome_name = prediction.get_genome_name(f_prefix)[0]

subset += list(prediction.get_genome_name("Scheffersomyces_spartinae")) + list(prediction.get_genome_name("Scheffersomyces_gosingicus"))

# write_to_file(f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.txt", subset)

In [9]:
subset

['g003178.m1_yHMPu5000035296_priceomyces_carsonii_160928.final',
 'g000189.m1_yHMPu5000035297_priceomyces_castillae_170307.final',
 'g003772.m1_yHMPu5000035660_priceomyces_haplophilus_160613.final',
 'g000985.m1_yHMPu5000034606_priceomyces_medius_180604.final',
 'g004064.m1_yHMPu5000035294_candida_fermenticarens_170307.final',
 'g004997.m1_yHMPu5000035295_priceomyces_melissophilus_201018.final',
 'g004714.m1_yHMPu5000041792_schwanniomyces_capriottii_170912.final',
 'g006752.m1_yHMPu5000038322_schwanniomyces_polymorphus_var_africanus_170713.final',
 'g007241.m1_yHMPu5000041780_Schwanniomyces_polymorphus_var_polymorphus_SPADES.final',
 'g004441.m1_yHRVM31_Schwanniomyces_sp_nov_plate33_SPADES.final',
 'g006004.m1_yHMPu5000041779_schwanniomyces_pseudopolymorphus_190924.final',
 'g005264.m1_yHMPu5000037844_schwanniomyces_vanrijiae_var_vanrijiae_180604.final',
 'g005840.m1_yHMPu5000041778_schwanniomyces_vanrijiae_var_yarrowii_170912.final',
 'g003605.m1_yHMPu5000037843_schwanniomyces_yamadae_170912.final',
 'g000513.m1_yHMPu5000034581_schwanniomyces_occidentalis_var_occidentalis_170713.final',
 'g003997.m1_yHMPu5000041781_schwanniomyces_occidentalis_var_persoonii_190924.final',
 'g000381.m1_yHMPu5000037857_scheffersomyces_spartiniae_170210.final',
 'g000063.m1_yHMPu5000038324_scheffersomyces_gosingicus_180604.final']

In [10]:
prediction.get_genome_name("Scheffersomyces_spartinae")

array(['g000381.m1_yHMPu5000037857_scheffersomyces_spartiniae_170210.final'],
      dtype=object)

In [11]:
prediction.consensus_preds[prediction.consensus_preds['FINAL_Tip_ID'] == "Schwanniomyces_capriottii"]

,name,sequence,adhunter_centers,adhunter_preds,tada_centers,tada_preds,adpred_preds,paddle_centers,paddle_preds,combined_preds,...,length,assembly_fullID_updated,Tip_ID,KEGG_name_no_haplomerger,Tip_ID_v2,FINAL_Tip_ID,Class,Order,Family,Genus
1451,g004714.m1_yHMPu5000041792_schwanniomyces_capr...,MSATTTNPMILSGDSLFEYSDFLNQPASNTISLENEIVPMKNHDVE...,"[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[122288.79, 73914.7, 81898.71, 108855.88, 9238...","[20.0, 21.0, 22.0, 23.0, 24.0, 25.0, 26.0, 27....","[0.60005105, 0.581217, 0.5605932, 0.5595167, 0...","[0.0013640228, 0.003110036, 0.013452053, 0.014...","[27.0, 28.0, 29.0, 30.0, 31.0, 32.0, 33.0, 34....","[5.3837976, 5.7084064, 5.989379, 6.1840262, 6....","[0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.6, ...",...,300,yHMPu5000041792_schwanniomyces_capriottii_170912,Schwanniomyces_capriottii_CBS2923,yHMPu5000041792_schwanniomyces_capriottii_170912,Schwanniomyces_capriottii,Schwanniomyces_capriottii,Pichiomycetes,Serinales,Debaryomycetaceae,Schwanniomyces

In [356]:
! grep -f "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.txt" -A 1 "../Gcn4/Gcn4_orthologs.fasta" > "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.fasta"
! mafft --auto "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.fasta" > "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft.fasta"

outputhat23=16
treein = 0
compacttree = 0
stacksize: 8176 kb
rescale = 1
All-to-all alignment.
tbfast-pair (aa) Version 7.526
alg=L, model=BLOSUM62, 2.00, -0.10, +0.10, noshift, amax=0.0
0 thread(s)

outputhat23=16
Loading 'hat3.seed' ...
done.
Writing hat3 for iterative refinement
rescale = 1
Gap Penalty = -1.53, +0.00, +0.00
tbutree = 1, compacttree = 0
Constructing a UPGMA tree ...
   10 / 18
done.

Progressive alignment ...
STEP    17 /17
done.
tbfast (aa) Version 7.526
alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
1 thread(s)

minimumweight = 0.000010
autosubalignment = 0.000000
nthread = 0
randomseed = 0
blosum 62 / kimura 200
poffset = 0
niter = 16
sueff_global = 0.100000
nadd = 16
Loading 'hat3' ... done.
rescale = 1

   10 / 18
Segment   1/  1    1- 357
STEP 003-009-1  identical.    identical.
Converged.

done
dvtditr (aa) Version 7.526
alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
0 thread(s)


Strategy:
 L-INS-i (Probably most accurate, very slow)
 Iterative refinement method (<16) with LOCAL pairwise alignment information

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

In [18]:
def mylayout(node):
    global i
    if node.is_leaf():
        name = node.get_leaf_names()
        new_name = prediction.get_tree_name(name[0])
        node.name = new_name
    else:
        F = TextFace(node.name, tight_text=True)
        add_face_to_node(F, node, column=0, position="branch-right")

t = PhyloTree("/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/saccharmycotina_TFs/Gcn4/gain_loss_F_subsets/iqtree/Priceomyces_carsonii_mafft.fasta.treefile", format=1)

ts = TreeStyle()

ts.layout_fn = mylayout

t.show(tree_style = ts)

In [40]:
t.write(format=0, outfile='../Gcn4/gain_loss_F_subsets/iqtree/Priceomyces_carsonii_mafft_new_names.fasta.treefile')

In [19]:
folder = "Gcn4"
prediction_subset = Predictions(f"../{folder}/{folder}_orthologs_consensus_predictions.pkl.gz",
                        "../Gcn4/gain_loss_F_subsets/iqtree/Priceomyces_carsonii_mafft_new_names.fasta.treefile",
                        "/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/phylogenetic_data/ALL_NAMES_FILE.xlsx")

In [24]:
int(53 / 2)

26

In [22]:
# start, end = get_coords(f"../Gcn4/gain_loss_F_subsets/{f_prefix}_mafft.fasta", genome_name, prediction.consensus_preds)
# This is for nucleotide sequence
prediction_subset.add_alignment_to_tree(["Priceomyces_melissophilus", "Scheffersomyces_spartinae"], 
                                    f"../Gcn4/gain_loss_F_subsets/{f_prefix}_nucleotide_mafft.fasta", 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_nucleotide_mafft_on_tree_second_gain_loss.pdf",
                                    fg_colors=fg_colors,
                                    align_start = 93,
                                    align_end=99,
                                    bg_colors=bg_colors, 
                                    # bg_2 = bg_colors_2,
                                    # highlight = ["Priceomyces_melissophilus", "Schwanniomyces_yamadae"]
                                    )

In [ ]:
# Gain and loss!
names = ["Priceomyces_carsonii", "Schwanniomyces_occidentalis_var._persoonii"] #, "Candida_boidinii"]
subset = prediction.get_species_subset(names)[1]
f_prefix = names[0]
genome_name = prediction.get_genome_name(f_prefix)[0]

# def write_to_file(file, names):
#     with open(file, "w+") as f:
#         for name in names:
#             f.write(name + "\n")

# write_to_file(f"../Gcn4/gain_loss_F_subsets/{f_prefix}.txt", subset)

# ! grep -f "../Gcn4/gain_loss_F_subsets/{f_prefix}.txt" -A 1 "../Gcn4/Gcn4_orthologs.fasta" > "../Gcn4/gain_loss_F_subsets/{f_prefix}.fasta"
# ! mafft --auto "../Gcn4/gain_loss_F_subsets/{f_prefix}.fasta" > "../Gcn4/gain_loss_F_subsets/{f_prefix}_mafft.fasta"

# start, end = get_coords(f"../Gcn4/gain_loss_F_subsets/{f_prefix}_nucleotide_mafft.fasta", genome_name, prediction.consensus_preds)

prediction.add_alignment_to_tree(names, 
                                    f"../Gcn4/gain_loss_F_subsets/{f_prefix}_nucleotide_mafft.fasta", 
                                    f"../Gcn4/gain_loss_F_subsets/{f_prefix}_nucleotide_mafft_on_tree.pdf",
                                    fg_colors=fg_colors,
                                    align_start = 44,
                                    align_end= 30, #end,
                                    bg_colors=bg_colors, 
                                    bg_2 = bg_colors_2,
                                    highlight = ["Priceomyces_carsonii", "Schwanniomyces_yamadae"]
                                    )

In [365]:
ancestral_seqs = pd.read_table("../Gcn4/gain_loss_F_subsets/iqtree/Priceomyces_carsonii_mafft.fasta.state", comment='#')

In [366]:
node1 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node1"]["State"]:
    node1 += aa

node1

'MTATIKTATATENRNPMIYTEDIDLFDDIGIMMKDTAATTTNGGNEIIEQVEPLVENISSHINNMNLNNNENEAGLHMDTPFNLHSTVLDSVFSNTVDEYDQLIDHTPMFEELDVFNTNDGHAVNSKDDWVALFGDADGIVLGSLEAATSKVTESYANEVVPQFTSESDSRKRAFDEVEAFEIELALDPAPVNTQVEESYNVQNDHITSKRQNAYATPNSSSSLPTPLLDEGKKRRRIGSVNFVSSASKSCTTSANVTPLLDGIDKVDHLGVVAYSKKTRSQPLEPIKVDSSDPVAVKRARNTEAARRSRARKMERMSQLELRVEDLMSEKEDLQNEVARLKDLLMLHGIPFEQ'

In [306]:
ancestral_seqs[ancestral_seqs["Node"] == "Node1"][ancestral_seqs["Site"] == 31]

/var/folders/34/1pw3__x51kdfyh3vk72f5vc80000gn/T/ipykernel_7376/3882714115.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ancestral_seqs[ancestral_seqs["Node"] == "Node1"][ancestral_seqs["Site"] == 31]

,Node,Site,State,p_A,p_R,p_N,p_D,p_C,p_Q,p_E,...,p_L,p_K,p_M,p_F,p_P,p_S,p_T,p_W,p_Y,p_V
4930,Node1,31,F,0.00007,0.00007,0.00002,0.0,0.00048,0.00004,0.0,...,0.46758,0.00001,0.0074,0.49789,0.00002,0.00093,0.0001,0.00003,0.00147,0.00484

In [367]:
node2 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node2"]["State"]:
    node2 += aa
node2

'MTATIKKAMSTTTKNPMILSGDSLMFESSGDLFNEPTTNSISLGNEIIPMKNHNVEELSSHLPTLDTDGEELNSGLHKTSPFNIHSSVLDSVFSNTLDENDQLVDHTPMFDELDVFIVNDGAKVNLKDDWVSLFGDESEPMLGSIDESNNVVKEEDLEDDILQSTTDTNSRKRLFSEVEELELELSFEFAPLKKQKSSSYKVQSDYLVDKHQDQLFTPNSSSTLPTPLLDNAKLSALVGSLDLVSSKPKKSSTSANVTPLLDGVKKVDHLGCVTYSKKQRSQPLAPVKVDSSDPVALKRARNTEAARRSRARKMERMGQLEVKVEELLSEKTDLENEVSRLKELLTNNGIQFEQ'

In [386]:
node3 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node3"]["State"]:
    node3 += aa
node3

'MTATIKKAMSATTTNPMILSGDSLMFESSGDLFNQPTTNSISLENEIIPMKNHNVEELSSHLPTLDEDGEELNSGLHKTSPFNIHSSVLDSVFSNTLDENDQLQDHTPMFDELDVFIVNDGAKVNLKDDWVSLFGGESEPMLGSIDESNNVVKEEDLDDDILQSTTDTNSRKRLFSEVEELELELSFEFAPLKKQKSSSYKVQSDYLVDKHQDQLFTPNSSSTLPTPLLDNAKLSALVGSLDLVSSKPKKSSTSANVTPLLDGVKKVDHLGCVTYSKKQRSQPLAPVKVDSSDPVVLKRARNTEAARRSRARKMERMGQLEVKVEELLSEKTDLENEVSRLKELLTNNGIQFEQ'

In [379]:
node5 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node5"]["State"]:
    node5 += aa
node5

'MTATIKKAMSATTTNPMILSGDSLMFESSGDFFNQPTSNSISLENEIIPMKNHNVEELSSNLPVLDTDGEELNSGLHKTSPFTIHSSVLDSVFSNTLDENDQLQDHTPMFDELDVFIVNDGAKVNLKDDWVSLFGAESESALGAIDESNNVVKEEDLKDDILPSTSDSASSKRLFSEVEELELELSFEFAPLKKQKTSSYKVSSDYLIDKHQDQLFTPNPSSTLPTPLLDNAKLSPLVGSLDLVSSKSRKSSTSANVTPLLDGVKKVDHLGCVTYSKKQRSQPLPPVEVESSDPVVLKRARNTEAARRSRARKMERMSQLEVKVEELISEKTDLENEVSRLKELLTANGIQFEQ'

In [394]:
node6 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node6"]["State"]:
    node6 += aa
node6

'LTATIKKAMSATTTNPMILSGDSLMFEYSGDFLNQPTSNTISLENEIVPMKNHNVEELSSNLPVLDHDIQELASGLHAKSPFTIHSSVLDSVFSSNLDENDQFQDQTPMFDELDVFIVNDGAKVNLKEDWVSLFGAESEAAINTADDSNTVVKDLDLMKDILPETAPSASNKRLFSEVEELELELSFEFAPAKKQQKTSYKVSSDLLSDVQQSQLFTPNPSSTLPTPLLDNAKPRKLVGSLDLVSSSSRVSQSSANVTPLLDGVKKVDHLGCVTYSKKQRTQPLPPVETASNDPVLLKRARNTEAARRSRARKMERMSQLEGKVEELIGEKTNLENEVSRLKELLTANGIQFEQ'

In [378]:
node12 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node12"]["State"]:
    node12 += aa
node12

'LTATIKKAMFTTVKSPMILSGDSFMFESSGDKFNEPSTDHVSYGDEIISTKHDGVDELSSHLPMFDTEAEEVDDGLHKASPFSIHSSVLDSVFSNTLDEEGQEVDQTPMFDELDVFIVNDGAKANLKEDWVSLFGDESEMMLGSGETSDPVVKEEDLEEELLQYTEKSESSKRLFSQDTALELELPSEFVPSKKQKNSSYKVSSDLFVDSQQNQLVTPNTSSTLATPLIDTSELRALVGSLDLVSSGQKKRSSSANVTPLLDGVTKVDRLGCVPYSKKQRSRPLAPVKIDGSDPVALKRARNTEAARRSRARKMERMGQLEEKVENLLSEKSDLESEVSRLKDLLTQNGIQFEQ'

In [388]:
node13 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node13"]["State"]:
    node13 += aa
node13

'LLATIKKAMFTTVKSPMILSGDSFMLESSGDKFNEPSTDHVSYGEDIISTKHDGVDELSSHLPMFDTEAEEVDDGLHKASPFSIHSSVLDSVFSNTLDEEGQEVDQTPMFDELDVFIVNDGAKANLKEDWVSLFGDESEMMLGSGEPSDPLVKEEDLEEELLMYTEKSPSSKRLFSQDTALELELQSESVPSNSQKNSSYKVSSDLFVDSKQNQLVTPNTSSTLATPLIDTTELKSLVGSLDLVSSGQKKRASSANVTPLLDGVTKVDSLGCVPYSKKQRSRPLAPVKIDGSDPVALKRARNTEAARRSRARKMERMGQLEEKVENLLSEKSDLESEVSRLKDLLTQNGIQFEQ'

In [17]:
t=PhyloTree("/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/phylogenetic_data/1175taxa_1403OGs_astral_length_rooted_lpp_added.tre")
t.show()

# Ancestral reconstruction 2

In [8]:
# Gain and loss!
names = ["Kuraishia_molischiana", "Kuraishia_borneana", "Kuraishia_cidri"] #, "Candida_boidinii"]
subset = prediction.get_species_subset(names)[1] + list(prediction.get_genome_name('Candida_boidinii'))
f_prefix = names[0]
genome_name = prediction.get_genome_name(f_prefix)[0]

write_to_file(f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.txt", subset)

NameError: name 'write_to_file' is not defined

In [9]:
prediction.get_genome_name('Candida_boidinii')

array(['g001518.m1_yHMPu5000034926_candida_boidinii_160519.final'],
      dtype=object)

In [17]:
prediction.get_ADs()

In [27]:
! grep -f "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.txt" -A 1 "../Gcn4/Gcn4_orthologs.fasta" > "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.fasta"
! mafft --auto "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}.fasta" > "../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft.fasta"

outputhat23=16
treein = 0
compacttree = 0
stacksize: 8176 kb
rescale = 1
All-to-all alignment.
tbfast-pair (aa) Version 7.526
alg=L, model=BLOSUM62, 2.00, -0.10, +0.10, noshift, amax=0.0
0 thread(s)

outputhat23=16
Loading 'hat3.seed' ...
done.
Writing hat3 for iterative refinement
rescale = 1
Gap Penalty = -1.53, +0.00, +0.00
tbutree = 1, compacttree = 0
Constructing a UPGMA tree ...
    0 / 8
done.

Progressive alignment ...
STEP     6 /7
Reallocating..done. *alloclen = 1570
STEP     7 /7
done.
tbfast (aa) Version 7.526
alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
1 thread(s)

minimumweight = 0.000010
autosubalignment = 0.000000
nthread = 0
randomseed = 0
blosum 62 / kimura 200
poffset = 0
niter = 16
sueff_global = 0.100000
nadd = 16
Loading 'hat3' ... done.
rescale = 1

    0 / 8
Segment   1/  1    1- 345
STEP 004-006-1  identical.
Converged.

done
dvtditr (aa) Version 7.526
alg=A, model=BLOSUM62, 1.53, -0.00, -0.00, noshift, amax=0.0
0 thread(s)


Strategy:
 L-INS-i (Probably most accurate, very slow)
 Iterative refinement method (<16) with LOCAL pairwise alignment information

If unsure which option to use, try 'mafft --auto input > output'.
For more information, see 'mafft --help', 'mafft --man' and the mafft page.

The default gap scoring scheme has been changed in version 7.110 (2013 Oct).
It tends to insert more gaps into gap-rich regions than previous versions.
To disable this change, add the --leavegappyregion option.

In [12]:
def mylayout(node):
    global i
    if node.is_leaf():
        name = node.get_leaf_names()
        new_name = prediction.get_tree_name(name[0])
        node.name = new_name
    else:
        F = TextFace(node.name, tight_text=True)
        add_face_to_node(F, node, column=0, position="branch-right")

t = PhyloTree("../Gcn4/gain_loss_F_subsets/iqtree/Kuraishia_molischiana_mafft.fasta.treefile", format=1)

ts = TreeStyle()

ts.layout_fn = mylayout

t.show(tree_style = ts)

In [43]:
t.write(format=0, outfile=f'../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft_new_names.fasta.treefile')

In [19]:
folder = "Gcn4"
prediction_subset = Predictions(f"../{folder}/{folder}_consensus_predictions.csv",
                        f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft_new_names.fasta.treefile",
                        "/Users/claireleblanc/Documents/grad_school/staller_lab/Evolution_stuff/phylogenetic_data/ALL_NAMES_FILE.xlsx")

In [27]:
start, end = get_coords(f"../Gcn4/gain_loss_F_subsets/{f_prefix}_mafft.fasta", genome_name, prediction.consensus_preds)
prediction_subset.add_alignment_to_tree(names, 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft.fasta", 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft_on_tree_gain_loss_trimmed_tree.pdf",
                                    fg_colors=fg_colors,
                                    align_start = 91,
                                    align_end=93,
                                    bg_colors=bg_colors
                                    # bg_2 = bg_colors_2,
                                    # highlight = ["Priceomyces_melissophilus", "Schwanniomyces_yamadae"]
                                    )

ESVFDAFAKSEPIDAKVKLEDADSFLGCMADLGLDPDESSELPSSSVDPMFIHASTIESVFNSPVETPMFAEPETWDSLFGEVEPLVEVDATSESKQES

In [ ]:
import alignment
alignment.add_alignment_to_tree(prediction,
                                    names, 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft.fasta", 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft_on_tree_gain_loss_trimmed_tree.pdf",
                                    fg_colors=fg_colors,
                                    align_start = 91,
                                    align_end=93,
                                    bg_colors=bg_colors

)

Warnning: [1167] terminal nodes could not be found in the alignment.

In [31]:
import alignment
alignment.add_alignment_to_tree(prediction,
                                    names, 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft.fasta", 
                                    f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft_on_tree_gain_loss_trimmed_full.pdf",
                                    fg_colors=fg_colors,
                                    align_start = 80,
                                    align_end=140,
                                    bg_colors=bg_colors

)

Warnning: [1167] terminal nodes could not be found in the alignment.

In [60]:
ancestral_seqs = pd.read_table(f"../Gcn4/gain_loss_F_subsets/iqtree/{f_prefix}_mafft.fasta.state", comment='#')

In [65]:
node5 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node5"]["State"]:
    node5 += aa
node5[91:93]

'LF'

In [66]:
node6 = ""
for aa in ancestral_seqs[ancestral_seqs["Node"] == "Node6"]["State"]:
    node6 += aa
node6[91:93]

'FF'